spring:
  datasource:
    url: jdbc:mysql://mysql:3306/employee_db
    username: employee
    password: employee
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate

security:
  jwt:
    secret: ${JWT_SECRET}
    expiration-seconds: 3600
